# DataSource configuration
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/oblog
        username: root
        password: xxxxxx
    servlet:
      multipart:
          max-file-size: 10MB  # 设置单个文件的最大大小
          max-request-size: 15MB  # 设置整个请求的最大大小
    data:
      redis:
          host: localhost       # 配置redis
          port: 6379
mybatis:
    configuration:
        map-underscore-to-camel-case: true
        #开启mysql数据响应表头中下划线命名、映射至pojo数据元类驼峰命名的自动转译功能
        #例如，数据库里create_time数据自动找到数据类里的createTime变量

        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 选择mybatis 报错形式为控制台log输出
    mapper-locations: classpath:mapper/**.xml



# TODO jwt-public-key?????springsecurity???


server:
    port: 8080
# Redis configuration

